### ISSUE TITLE
unknown mat file type, version 49, 50

### ISSUE THREAD

**Issue by liyuanyaun** [wuhaozhe/style_avatar#4]
when i load "BFM_model_front.mat", the error "unknown mat file type, version 49, 50" happened? can you share what version scipy you install @wuhaozhe

**Comment by wuhaozhe** [comment]
Hi, can you show me the size of "BFM_model_front.mat", which should be 121MB. 

We store "BFM_model_front.mat" with git lfs. If its size is only a few bytes, it must be a pointer of git lfs rather than the real file. To solve this problem, you can install git lfs and run `git lfs checkout ./deep_3drecon/BFM/BFM_model_front.mat`. Optionally, there is a much easier solution, you can directly download "BFM_model_front.mat" from github and put it into the corresponding folder.

**Comment by wuhaozhe** [comment]
Hey, we have upload a new link for downloading BFM_model_front.mat, see the readme

**Comment by liyuanyaun** [comment]
> Hey, we have upload a new link for downloading BFM_model_front.mat, see the readme

thank you, i have solved my problem
